# This grabs hadoop-VERSION-snapshot.tar from the hadoop-dist/target directory and create a hadoop docker image
version: '3.3'
name: hadoop-repro
services:
  namenode:
    image: hdfs-repro:latest
    restart: always
    environment:
      - HDFS_DATANODE_USER=root
      # Note this!
      - APP_RANNODES_CLEAR=true
    ports:
      - "9870:9870"
      - "8088:8088"
    volumes:
      - ./core-site.xml:/opt/hadoop-3.3.0/etc/hadoop/core-site.xml
      - ./hdfs-site.xml:/opt/hadoop-3.3.0/etc/hadoop/hdfs-site.xml
      - ./mapred-site.xml:/opt/hadoop-3.3.0/etc/hadoop/mapred-site.xml
      - ./yarn-site.xml:/opt/hadoop-3.3.0/etc/hadoop/yarn-site.xml
      - ./rack-topo.sh:/opt/rack-topo.sh
    entrypoint: bash namenode-entrypoint.sh
    networks:
      - intra

  datanode:
    image: hdfs-repro:latest
    privileged: true
    restart: always
    volumes:
      - ./core-site.xml:/opt/hadoop-3.3.0/etc/hadoop/core-site.xml
      - ./hdfs-site.xml:/opt/hadoop-3.3.0/etc/hadoop/hdfs-site.xml
      - ./mapred-site.xml:/opt/hadoop-3.3.0/etc/hadoop/mapred-site.xml
      - ./yarn-site.xml:/opt/hadoop-3.3.0/etc/hadoop/yarn-site.xml
      - ./rack-topo.sh:/opt/rack-topo.sh
    environment:
      # Note this!
      - APP_RANNODES_CLEAR=true
    entrypoint: bash datanode-entrypoint.sh
    networks:
      - intra
    deploy:
      replicas: 25

networks:
    intra: